name: Create Web Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Create Web Release
      uses: lamkasdev/zip-release@master
      with:
        directory: 'client/build'
        filename: 'build.zip'
    - name: Upload build.zip
      uses: actions/upload-artifact@v2
      with:
        name: build.zip
        path: client/build/build.zip
